CREATE TABLE song
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title        VARCHAR(255),
    artist       VARCHAR(255),
    album        VARCHAR(255),
    release_year INTEGER,
    genre        VARCHAR(255)                            NOT NULL,
    duration     INTEGER,
    CONSTRAINT pk_song PRIMARY KEY (id)
);


INSERT INTO song (title, artist, album, release_year, genre, duration) VALUES
('Blinding Lights', 'The Weeknd', 'After Hours', 2020, 'POP', 200),
('Bohemian Rhapsody', 'Queen', 'A Night at the Opera', 1975, 'ROCK', 354),
('Lose Yourself', 'Eminem', '8 Mile', 2002, 'HIPHOP', 326),
('Take Five', 'The Dave Brubeck Quartet', 'Time Out', 1959, 'JAZZ', 324),
('Moonlight Sonata', 'Beethoven', NULL, 1801, 'CLASSICAL', 450),
('HUMBLE.', 'Kendrick Lamar', 'DAMN.', 2017, 'HIPHOP', 177),
('Alright', 'Kendrick Lamar', 'To Pimp a Butterfly', 2015, 'HIPHOP', 215),
('DNA.', 'Kendrick Lamar', 'DAMN.', 2017, 'HIPHOP', 185),
('King Kunta', 'Kendrick Lamar', 'To Pimp a Butterfly', 2015, 'HIPHOP', 220),
('Swimming Pools (Drank)', 'Kendrick Lamar', 'good kid, m.A.A.d city', 2012, 'HIPHOP', 235),
('Money Trees', 'Kendrick Lamar', 'good kid, m.A.A.d city', 2012, 'HIPHOP', 386),
('Backseat Freestyle', 'Kendrick Lamar', 'good kid, m.A.A.d city', 2012, 'HIPHOP', 244),
('The Blacker the Berry', 'Kendrick Lamar', 'To Pimp a Butterfly', 2015, 'HIPHOP', 315),
('LOYALTY.', 'Kendrick Lamar', 'DAMN.', 2017, 'HIPHOP', 244),
('B$$$$$$, Dont Kill My Vibe', 'Kendrick Lamar', 'good kid, m.A.A.d city', 2012, 'HIPHOP', 312);