CREATE TABLE app_user
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255)                            NOT NULL,
    password VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_appuser PRIMARY KEY (id)
);

ALTER TABLE app_user
    ADD CONSTRAINT uc_appuser_username UNIQUE (username);



INSERT INTO app_user (username, password) VALUES
('alice', '$2a$10$rRI0daZpyhORtmto3q8xj.RLWAW7Ws8s519/qQ4P7ze/w84rVI3qe'),
('bob', '$2a$10$rRI0daZpyhORtmto3q8xj.RLWAW7Ws8s519/qQ4P7ze/w84rVI3qe'),
('charlie', '$2a$10$rRI0daZpyhORtmto3q8xj.RLWAW7Ws8s519/qQ4P7ze/w84rVI3qe');