server:
  port: 8082

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    # url: jdbc:postgresql://localhost:5432/tunz
    # username: wiroot
    # password: wiroot1234
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    com.progressoft: DEBUG